# @format

name: Deploy (Deprecated)

on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [17.6]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install Dependencies (npm install)
              run: |
                  npm install

            - name: Building the project (npm run build)
              run: |
                  ls -al
                  docusaurus build
